// Generated by https://quicktype.io

export interface CreditsResponse {
    data: Datum[];
}

export interface Datum {
    id: number;
    name: string;
    value: number;
}

export interface Credit {
    id: number;
    name: string;
    value: number;
}
